#!/usr/bin/env sh
set -e

REALPATH="$0"
while test -L "$REALPATH"; do
  REALPATH="`readlink "$REALPATH"`"
done
REALPATH="`cd "\`dirname "$REALPATH"\`" && pwd -P`"

cd "$REALPATH"
export PATH="$REALPATH/bin:$PATH"
gru lua/patch.lua -y "$@"
