#!/usr/bin/env sh
set -e

REALPATH="$0"
while test -L "$REALPATH"; do
  REALPATH="`readlink "$REALPATH"`"
done
REALPATH="`cd "\`dirname "$REALPATH"\`" && pwd -P`"

cd "$REALPATH"
export PATH="$REALPATH/bin:$PATH"
echo 45e | gzinject -a genkey -k common-key.bin >/dev/null
gru lua/patch-wad.lua -y "$@" || true
rm -rf common-key.bin wadextract
