local version_suffix
if wiivc then version_suffix = "-vc" else version_suffix = "" end

rom_table =
{
  [0xD423E8B0]  = {
                    game        = "oot",
                    version     = "1.0",
                    region      = "j",
                    code_ind    = 27,
                    code_ram    = 0x800110A0,
                    data_dir    = "oot-1.0",
                    gz_version  = "oot-1.0" .. version_suffix,
                    gz_name     = "gz-oot-1.0-j" .. version_suffix,
                    title_id    = "NG0J",
                  },
  [0xCD16C529]  = {
                    game        = "oot",
                    version     = "1.0",
                    region      = "u",
                    code_ind    = 27,
                    code_ram    = 0x800110A0,
                    data_dir    = "oot-1.0",
                    gz_version  = "oot-1.0" .. version_suffix,
                    gz_name     = "gz-oot-1.0-u" .. version_suffix,
                    title_id    = "NG0E",
                  },
  [0x26E73887]  = {
                    game        = "oot",
                    version     = "1.1",
                    region      = "j",
                    code_ind    = 27,
                    code_ram    = 0x800110A0,
                    data_dir    = "oot-1.1",
                    gz_version  = "oot-1.1" .. version_suffix,
                    gz_name     = "gz-oot-1.1-j" .. version_suffix,
                    title_id    = "NG1J",
                  },
  [0x3FD2151E]  = {
                    game        = "oot",
                    version     = "1.1",
                    region      = "u",
                    code_ind    = 27,
                    code_ram    = 0x800110A0,
                    data_dir    = "oot-1.1",
                    gz_version  = "oot-1.1" .. version_suffix,
                    gz_name     = "gz-oot-1.1-u" .. version_suffix,
                    title_id    = "NG1E",
                  },
  [0x2B2721BA]  = {
                    game        = "oot",
                    version     = "1.2",
                    region      = "j",
                    code_ind    = 27,
                    code_ram    = 0x800116E0,
                    data_dir    = "oot-1.2",
                    gz_version  = "oot-1.2" .. version_suffix,
                    gz_name     = "gz-oot-1.2-j" .. version_suffix,
                    title_id    = "NG2J",
                  },
  [0x32120C23]  = {
                    game        = "oot",
                    version     = "1.2",
                    region      = "u",
                    code_ind    = 27,
                    code_ram    = 0x800116E0,
                    data_dir    = "oot-1.2",
                    gz_version  = "oot-1.2" .. version_suffix,
                    gz_name     = "gz-oot-1.2-u" .. version_suffix,
                    title_id    = "NG2E",
                  },
  [0x122FF261]  = {
                    game        = "oot",
                    version     = "mq",
                    region      = "j",
                    code_ind    = 27,
                    code_ram    = 0x80010EE0,
                    data_dir    = "oot-mq-j",
                    gz_version  = "oot-mq-j" .. version_suffix,
                    gz_name     = "gz-oot-mq-j" .. version_suffix,
                    title_id    = "NGQJ",
                  },
  [0xC744C4DB]  = {
                    game        = "oot",
                    version     = "mq",
                    region      = "u",
                    code_ind    = 27,
                    code_ram    = 0x80010EE0,
                    data_dir    = "oot-mq-u",
                    gz_version  = "oot-mq-u" .. version_suffix,
                    gz_name     = "gz-oot-mq-u" .. version_suffix,
                    title_id    = "NGQE",
                  },
  [0x1C6CE8CB]  = {
                    game        = "oot",
                    version     = "gc",
                    region      = "j",
                    code_ind    = 27,
                    code_ram    = 0x80010EE0,
                    data_dir    = "oot-gc-j",
                    gz_version  = "oot-gc-j" .. version_suffix,
                    gz_name     = "gz-oot-gc-j" .. version_suffix,
                    title_id    = "NGCJ",
                  },
  [0x346DE3AE]  = {
                    game        = "oot",
                    version     = "gc",
                    region      = "u",
                    code_ind    = 27,
                    code_ram    = 0x80010EE0,
                    data_dir    = "oot-gc-u",
                    gz_version  = "oot-gc-u" .. version_suffix,
                    gz_name     = "gz-oot-gc-u" .. version_suffix,
                    title_id    = "NGCE",
                  },
  [0x8C5B90C1]  = {
                    game        = "oot",
                    version     = "ce",
                    region      = "j",
                    code_ind    = 27,
                    code_ram    = 0x80010EE0,
                    data_dir    = "oot-ce-j",
                    gz_version  = "oot-ce-j" .. version_suffix,
                    gz_name     = "gz-oot-ce-j" .. version_suffix,
                    title_id    = "NGEJ",
                  },
}

vc_table =
{
  [0xC74E596B] = "NACE",
  [0x46E8C795] = "NACJ",
}
